### ISSUE TITLE
Multiple sites on same port with different hostname?

### ISSUE THREAD

**Issue by computersrmyfriends** [DFabric/dppm#3]
Is it possible to run multiple sites with the same port but different hostnames with dppm?

Thanks

**Comment by j8r** [comment]
To do this, you'll need a web server like Caddy, Nginx or Apache.

Each application/site must have its own port, but they can be forwarded through a reverse proxy that expose 80/443 (http/https). 

The support of Caddy will come soon, I've just finished the [API to handle its configurations](https://github.com/j8r/caddy-api).

[Caddy](https://caddyserver.com/) has auto-https with Let's Encrypt, but we need of course a valid FQDN domain name, that will be checked.

Since we support a web server, PHP applications are also coming soon.

**Comment by computersrmyfriends** [comment]
Yes, if it can just help me deploy multiple websites out of the box, it will really be very helpful. I can use it in production for deploying and managing multiple sites.

**Comment by j8r** [comment]
DPPM is mainly meant for self-hosted use, typically single VPS/home-server machine.
Furthermore, it only deploys vanilla applications, not custom ones.

If you plan to manage websites for customers that are provided by them, for now I recommend you using Docker Swarm instead.
You'll be able to set up a HA simply across multiple machines, and have a nice UI like [Portainer](https://portainer.io/).
