### ISSUE TITLE
System groups are not removed when uninstalling dppm

### ISSUE THREAD

**Issue by dtrckd** [DFabric/dppm#6]
This leads to error when adding application after having uninstalled/reinstalled dppm.
As for example this one: 

```
ERR! Add failed - application deleted: /srv/dppm/app/default-group/riot-web
ERR! group name `_riot-web` already taken: 9004
```

**Comment by j8r** [comment]
Thanks @dtrckd , fixed in master.
This error was related to self-contained applications (sometimes required for PHP/HTML apps).
As a fix for your current system, you can remove the use and group line in `/etc/passwd` and `/etc/group` with `sed -i '/_riot-web/d' thefile, or manually. It should not happen again on future uninstallations.

**Comment by j8r** [comment]
Thanks @dtrckd , fixed in master.
This error was related to self-contained applications (sometimes required for PHP/HTML apps).
As a fix for your current system, you can remove the use and group line in `/etc/passwd` and `/etc/group` with `sed -i '/_riot-web/d' thefile`, or manually. It should not happen again on future uninstallations.
